
    name: Example Workflow

    on:
      push:
        branches:
          - main

    jobs:
      test:
        runs-on: ubuntu-latest
        steps:
          - name: 22f2001532@ds.study.iitm.ac.in
            run: echo "Hello, world!"
    